/*
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.github.freeclimbapi;

import com.github.freeclimbapi.enums.*;
import com.github.freeclimbapi.models.*;
import java.util.*;
import org.junit.Assert;
import org.junit.Test;
import org.threeten.bp.OffsetDateTime;

/** Model tests for CallResult */
public class CallResultTest {

    private final CallResult model = new CallResult();

    /** Test the property 'uri' */
    @Test
    public void uriTest() {

        model.setUri("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getUri());
    }

    /** Test the property 'dateCreated' */
    @Test
    public void dateCreatedTest() {

        model.setDateCreated("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getDateCreated());
    }

    /** Test the property 'dateUpdated' */
    @Test
    public void dateUpdatedTest() {

        model.setDateUpdated("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getDateUpdated());
    }

    /** Test the property 'revision' */
    @Test
    public void revisionTest() {

        model.setRevision(1);
        Assert.assertEquals(1, (int) model.getRevision());
    }

    /** Test the property 'dateCreatedISO' */
    @Test
    public void dateCreatedISOTest() {
        model.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));
        Assert.assertEquals(
                OffsetDateTime.parse("2022-07-05T15:17:05Z"), model.getDateCreatedISO());
    }

    /** Test the property 'dateUpdatedISO' */
    @Test
    public void dateUpdatedISOTest() {
        model.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));
        Assert.assertEquals(
                OffsetDateTime.parse("2022-07-05T15:17:05Z"), model.getDateUpdatedISO());
    }

    /** Test the property 'callId' */
    @Test
    public void callIdTest() {

        model.setCallId("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getCallId());
    }

    /** Test the property 'parentCallId' */
    @Test
    public void parentCallIdTest() {

        model.setParentCallId("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getParentCallId());
    }

    /** Test the property 'accountId' */
    @Test
    public void accountIdTest() {

        model.setAccountId("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getAccountId());
    }

    /** Test the property 'from' */
    @Test
    public void fromTest() {

        model.setFrom("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getFrom());
    }

    /** Test the property 'to' */
    @Test
    public void toTest() {

        model.setTo("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getTo());
    }

    /** Test the property 'phoneNumberId' */
    @Test
    public void phoneNumberIdTest() {

        model.setPhoneNumberId("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getPhoneNumberId());
    }

    /** Test the property 'status' */
    @Test
    public void statusTest() {
        model.setStatus(CallStatus.QUEUED);
        Assert.assertEquals(model.getStatus(), CallStatus.QUEUED);
        model.setStatus(CallStatus.RINGING);
        Assert.assertEquals(model.getStatus(), CallStatus.RINGING);
        model.setStatus(CallStatus.IN_PROGRESS);
        Assert.assertEquals(model.getStatus(), CallStatus.IN_PROGRESS);
        model.setStatus(CallStatus.CANCELED);
        Assert.assertEquals(model.getStatus(), CallStatus.CANCELED);
        model.setStatus(CallStatus.COMPLETED);
        Assert.assertEquals(model.getStatus(), CallStatus.COMPLETED);
        model.setStatus(CallStatus.FAILED);
        Assert.assertEquals(model.getStatus(), CallStatus.FAILED);
        model.setStatus(CallStatus.BUSY);
        Assert.assertEquals(model.getStatus(), CallStatus.BUSY);
        model.setStatus(CallStatus.NO_ANSWER);
        Assert.assertEquals(model.getStatus(), CallStatus.NO_ANSWER);
    }

    /** Test the property 'startTime' */
    @Test
    public void startTimeTest() {

        model.setStartTime("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getStartTime());
    }

    /** Test the property 'startTimeISO' */
    @Test
    public void startTimeISOTest() {
        model.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));
        Assert.assertEquals(OffsetDateTime.parse("2022-07-05T15:17:05Z"), model.getStartTimeISO());
    }

    /** Test the property 'connectTime' */
    @Test
    public void connectTimeTest() {

        model.setConnectTime("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getConnectTime());
    }

    /** Test the property 'connectTimeISO' */
    @Test
    public void connectTimeISOTest() {
        model.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));
        Assert.assertEquals(
                OffsetDateTime.parse("2022-07-05T15:17:05Z"), model.getConnectTimeISO());
    }

    /** Test the property 'endTime' */
    @Test
    public void endTimeTest() {

        model.setEndTime("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getEndTime());
    }

    /** Test the property 'endTimeISO' */
    @Test
    public void endTimeISOTest() {
        model.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));
        Assert.assertEquals(OffsetDateTime.parse("2022-07-05T15:17:05Z"), model.getEndTimeISO());
    }

    /** Test the property 'duration' */
    @Test
    public void durationTest() {

        model.setDuration(1);
        Assert.assertEquals(1, (int) model.getDuration());
    }

    /** Test the property 'connectDuration' */
    @Test
    public void connectDurationTest() {

        model.setConnectDuration(1);
        Assert.assertEquals(1, (int) model.getConnectDuration());
    }

    /** Test the property 'audioStreamDuration' */
    @Test
    public void audioStreamDurationTest() {

        model.setAudioStreamDuration(1);
        Assert.assertEquals(1, (int) model.getAudioStreamDuration());
    }

    /** Test the property 'direction' */
    @Test
    public void directionTest() {
        model.setDirection(CallDirection.INBOUND);
        Assert.assertEquals(model.getDirection(), CallDirection.INBOUND);
        model.setDirection(CallDirection.OUTBOUND_API);
        Assert.assertEquals(model.getDirection(), CallDirection.OUTBOUND_API);
        model.setDirection(CallDirection.OUTBOUND_DIAL);
        Assert.assertEquals(model.getDirection(), CallDirection.OUTBOUND_DIAL);
    }

    /** Test the property 'answeredBy' */
    @Test
    public void answeredByTest() {
        model.setAnsweredBy(AnsweredBy.HUMAN);
        Assert.assertEquals(model.getAnsweredBy(), AnsweredBy.HUMAN);
        model.setAnsweredBy(AnsweredBy.MACHINE);
        Assert.assertEquals(model.getAnsweredBy(), AnsweredBy.MACHINE);
    }

    /** Test the property 'callerName' */
    @Test
    public void callerNameTest() {

        model.setCallerName("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getCallerName());
    }

    /** Test the property 'webRTC' */
    @Test
    public void webRTCTest() {
        model.setWebRTC(false);
        Assert.assertEquals(false, model.getWebRTC());
    }

    /** Test the property 'subresourceUris' */
    @Test
    public void subresourceUrisTest() {

        CallResultAllOfSubresourceUris object = new CallResultAllOfSubresourceUris();
        model.setSubresourceUris(object);
        Assert.assertEquals(object.getClass(), CallResultAllOfSubresourceUris.class);
    }

    /** Test the property 'applicationId' */
    @Test
    public void applicationIdTest() {

        model.setApplicationId("TEST_STRING");
        Assert.assertEquals("TEST_STRING", model.getApplicationId());
    }

    /** Test the method 'equalsTrue' */
    @Test
    public void equalsTrueTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.QUEUED);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.INBOUND);

        test1.setAnsweredBy(AnsweredBy.HUMAN);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        CallResult test2 = new CallResult();

        test2.setUri("TS");

        test2.setDateCreated("TS");

        test2.setDateUpdated("TS");

        test2.setRevision(1);

        test2.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setCallId("TS");

        test2.setParentCallId("TS");

        test2.setAccountId("TS");

        test2.setFrom("TS");

        test2.setTo("TS");

        test2.setPhoneNumberId("TS");

        test2.setStatus(CallStatus.QUEUED);

        test2.setStartTime("TS");

        test2.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setConnectTime("TS");

        test2.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setEndTime("TS");

        test2.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setDuration(1);

        test2.setConnectDuration(1);

        test2.setAudioStreamDuration(1);

        test2.setDirection(CallDirection.INBOUND);

        test2.setAnsweredBy(AnsweredBy.HUMAN);

        test2.setCallerName("TS");

        test2.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject2 =
                testCallResultAllOfSubresourceUrisObject;
        test2.setSubresourceUris(testCallResultAllOfSubresourceUrisObject2);

        test2.setApplicationId("TS");

        Assert.assertTrue(test1.equals(test2));
    }

    /** Test the method 'equalsFalse' */
    @Test
    public void equalsFalseTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.RINGING);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.OUTBOUND_API);

        test1.setAnsweredBy(AnsweredBy.MACHINE);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        CallResult test2 = new CallResult();

        test2.setUri("TS2");

        test2.setDateCreated("TS2");

        test2.setDateUpdated("TS2");

        test2.setRevision(0);

        test2.setDateCreatedISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setDateUpdatedISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setCallId("TS2");

        test2.setParentCallId("TS2");

        test2.setAccountId("TS2");

        test2.setFrom("TS2");

        test2.setTo("TS2");

        test2.setPhoneNumberId("TS2");

        test2.setStatus(CallStatus.QUEUED);

        test2.setStartTime("TS2");

        test2.setStartTimeISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setConnectTime("TS2");

        test2.setConnectTimeISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setEndTime("TS2");

        test2.setEndTimeISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setDuration(0);

        test2.setConnectDuration(0);

        test2.setAudioStreamDuration(0);

        test2.setDirection(CallDirection.INBOUND);

        test2.setAnsweredBy(AnsweredBy.HUMAN);

        test2.setCallerName("TS2");

        test2.setWebRTC(false);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject2 =
                new CallResultAllOfSubresourceUris();
        test2.setSubresourceUris(testCallResultAllOfSubresourceUrisObject2);

        test2.setApplicationId("TS2");

        Assert.assertFalse(test1.equals(test2));
    }

    /** Test the method 'hashCodeType' */
    @Test
    public void hashCodeTypeTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.QUEUED);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.INBOUND);

        test1.setAnsweredBy(AnsweredBy.HUMAN);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        int hashCode1 = test1.hashCode();
        Assert.assertTrue(Integer.class.isInstance(hashCode1));
    }

    /** Test the method 'toStringEquals' */
    @Test
    public void toStringEqualsTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.QUEUED);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.INBOUND);

        test1.setAnsweredBy(AnsweredBy.HUMAN);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        CallResult test2 = new CallResult();

        test2.setUri("TS");

        test2.setDateCreated("TS");

        test2.setDateUpdated("TS");

        test2.setRevision(1);

        test2.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setCallId("TS");

        test2.setParentCallId("TS");

        test2.setAccountId("TS");

        test2.setFrom("TS");

        test2.setTo("TS");

        test2.setPhoneNumberId("TS");

        test2.setStatus(CallStatus.QUEUED);

        test2.setStartTime("TS");

        test2.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setConnectTime("TS");

        test2.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setEndTime("TS");

        test2.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setDuration(1);

        test2.setConnectDuration(1);

        test2.setAudioStreamDuration(1);

        test2.setDirection(CallDirection.INBOUND);

        test2.setAnsweredBy(AnsweredBy.HUMAN);

        test2.setCallerName("TS");

        test2.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject2 =
                testCallResultAllOfSubresourceUrisObject;
        test2.setSubresourceUris(testCallResultAllOfSubresourceUrisObject2);

        test2.setApplicationId("TS");

        String toString1 = test1.toString();
        String toString2 = test2.toString();
        Assert.assertEquals(toString1, toString2);
    }

    /** Test the method 'hashCodeEqualsTrue' */
    @Test
    public void hashCodeEqualsTrueTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.QUEUED);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.INBOUND);

        test1.setAnsweredBy(AnsweredBy.HUMAN);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        CallResult test2 = new CallResult();

        test2.setUri("TS");

        test2.setDateCreated("TS");

        test2.setDateUpdated("TS");

        test2.setRevision(1);

        test2.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setCallId("TS");

        test2.setParentCallId("TS");

        test2.setAccountId("TS");

        test2.setFrom("TS");

        test2.setTo("TS");

        test2.setPhoneNumberId("TS");

        test2.setStatus(CallStatus.QUEUED);

        test2.setStartTime("TS");

        test2.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setConnectTime("TS");

        test2.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setEndTime("TS");

        test2.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test2.setDuration(1);

        test2.setConnectDuration(1);

        test2.setAudioStreamDuration(1);

        test2.setDirection(CallDirection.INBOUND);

        test2.setAnsweredBy(AnsweredBy.HUMAN);

        test2.setCallerName("TS");

        test2.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject2 =
                testCallResultAllOfSubresourceUrisObject;
        test2.setSubresourceUris(testCallResultAllOfSubresourceUrisObject2);

        test2.setApplicationId("TS");

        Assert.assertEquals(test1.hashCode(), test2.hashCode());
    }

    /** Test the method 'hashCodeEqualsFalse' */
    @Test
    public void hashCodeEqualsFalseTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.RINGING);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.OUTBOUND_API);

        test1.setAnsweredBy(AnsweredBy.MACHINE);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        CallResult test2 = new CallResult();

        test2.setUri("TS2");

        test2.setDateCreated("TS2");

        test2.setDateUpdated("TS2");

        test2.setRevision(0);

        test2.setDateCreatedISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setDateUpdatedISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setCallId("TS2");

        test2.setParentCallId("TS2");

        test2.setAccountId("TS2");

        test2.setFrom("TS2");

        test2.setTo("TS2");

        test2.setPhoneNumberId("TS2");

        test2.setStatus(CallStatus.QUEUED);

        test2.setStartTime("TS2");

        test2.setStartTimeISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setConnectTime("TS2");

        test2.setConnectTimeISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setEndTime("TS2");

        test2.setEndTimeISO(OffsetDateTime.parse("2024-07-05T15:17:05Z"));

        test2.setDuration(0);

        test2.setConnectDuration(0);

        test2.setAudioStreamDuration(0);

        test2.setDirection(CallDirection.INBOUND);

        test2.setAnsweredBy(AnsweredBy.HUMAN);

        test2.setCallerName("TS2");

        test2.setWebRTC(false);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject2 =
                new CallResultAllOfSubresourceUris();
        test2.setSubresourceUris(testCallResultAllOfSubresourceUrisObject2);

        test2.setApplicationId("TS2");

        Assert.assertNotEquals(test1.hashCode(), test2.hashCode());
    }

    /** Test the method 'toStringType' */
    @Test
    public void toStringTypeTest() {
        CallResult test1 = new CallResult();

        test1.setUri("TS");

        test1.setDateCreated("TS");

        test1.setDateUpdated("TS");

        test1.setRevision(1);

        test1.setDateCreatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDateUpdatedISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setCallId("TS");

        test1.setParentCallId("TS");

        test1.setAccountId("TS");

        test1.setFrom("TS");

        test1.setTo("TS");

        test1.setPhoneNumberId("TS");

        test1.setStatus(CallStatus.QUEUED);

        test1.setStartTime("TS");

        test1.setStartTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setConnectTime("TS");

        test1.setConnectTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setEndTime("TS");

        test1.setEndTimeISO(OffsetDateTime.parse("2022-07-05T15:17:05Z"));

        test1.setDuration(1);

        test1.setConnectDuration(1);

        test1.setAudioStreamDuration(1);

        test1.setDirection(CallDirection.INBOUND);

        test1.setAnsweredBy(AnsweredBy.HUMAN);

        test1.setCallerName("TS");

        test1.setWebRTC(true);

        CallResultAllOfSubresourceUris testCallResultAllOfSubresourceUrisObject =
                new CallResultAllOfSubresourceUris();
        test1.setSubresourceUris(testCallResultAllOfSubresourceUrisObject);

        test1.setApplicationId("TS");

        String toString1 = test1.toString();
        Assert.assertTrue(String.class.isInstance(toString1));
    }
}
