/*
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.github.freeclimbapi;

import com.github.freeclimbapi.enums.*;
import com.github.freeclimbapi.models.*;
import java.util.*;
import org.junit.Assert;
import org.junit.Test;

/** Model tests for UpdateCallRequestStatus */
public class UpdateCallRequestStatusTest {

    @Test
    public void testCANCELEDShouldWork() {

        UpdateCallRequestStatus test = UpdateCallRequestStatus.CANCELED;
        Assert.assertEquals(test.getClass(), UpdateCallRequestStatus.class);
    }

    @Test
    public void testCANCELEDShouldSerializeToEnum() {

        UpdateCallRequestStatus expectedValue = UpdateCallRequestStatus.CANCELED;
        UpdateCallRequestStatus calculatedValue = UpdateCallRequestStatus.fromValue("canceled");
        Assert.assertEquals(expectedValue, calculatedValue);
    }

    @Test
    public void testCANCELEDShouldDeserializeToString() {
        UpdateCallRequestStatus test = UpdateCallRequestStatus.CANCELED;
        String expectedValue = "canceled";
        String calculatedValue = test.toString();
        Assert.assertEquals(expectedValue, calculatedValue);
    }

    @Test
    public void testCOMPLETEDShouldWork() {

        UpdateCallRequestStatus test = UpdateCallRequestStatus.COMPLETED;
        Assert.assertEquals(test.getClass(), UpdateCallRequestStatus.class);
    }

    @Test
    public void testCOMPLETEDShouldSerializeToEnum() {

        UpdateCallRequestStatus expectedValue = UpdateCallRequestStatus.COMPLETED;
        UpdateCallRequestStatus calculatedValue = UpdateCallRequestStatus.fromValue("completed");
        Assert.assertEquals(expectedValue, calculatedValue);
    }

    @Test
    public void testCOMPLETEDShouldDeserializeToString() {
        UpdateCallRequestStatus test = UpdateCallRequestStatus.COMPLETED;
        String expectedValue = "completed";
        String calculatedValue = test.toString();
        Assert.assertEquals(expectedValue, calculatedValue);
    }
}
