/*
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.github.freeclimbapi.models;

import com.github.freeclimbapi.JSON;
import com.github.freeclimbapi.enums.*;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.*;
import java.util.Objects;

/**
 * The digit sequence defined in the callControlSequence attribute of the AddToConference PerCL
 * command has been entered by the Conference participant. A PerCL response is expected. If invalid
 * PerCL is provided, the call leg which triggered this webhook will terminate.
 */
@ApiModel(
        description =
                "The digit sequence defined in the callControlSequence attribute of the"
                    + " AddToConference PerCL command has been entered by the Conference"
                    + " participant. A PerCL response is expected. If invalid PerCL is provided,"
                    + " the call leg which triggered this webhook will terminate.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CallControlWebhook extends Webhook {
    public static CallControlWebhook deserialize(String payload) {
        return (CallControlWebhook) (new JSON().getGson().fromJson(payload, Webhook.class));
    }

    public static String getDiscriminatorValue() {
        return "callControl";
    }

    public static final String SERIALIZED_NAME_REQUEST_TYPE = "requestType";

    @SerializedName(SERIALIZED_NAME_REQUEST_TYPE)
    protected String requestType;

    public static final String SERIALIZED_NAME_CALL_ID = "callId";

    @SerializedName(SERIALIZED_NAME_CALL_ID)
    private String callId;

    public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";

    @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
    private String accountId;

    public static final String SERIALIZED_NAME_CONFERENCE_ID = "conferenceId";

    @SerializedName(SERIALIZED_NAME_CONFERENCE_ID)
    private String conferenceId;

    public static final String SERIALIZED_NAME_DIGITS = "digits";

    @SerializedName(SERIALIZED_NAME_DIGITS)
    private String digits;

    public CallControlWebhook() {
        this.requestType = this.getClass().getSimpleName();
    }

    public CallControlWebhook requestType(String requestType) {

        this.requestType = requestType;
        return this;
    }

    /**
     * Context or reason why this request is being made. Will be callControl.
     *
     * @return requestType
     */
    @javax.annotation.Nullable
    @ApiModelProperty(
            value = "Context or reason why this request is being made. Will be callControl.")
    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    public CallControlWebhook callId(String callId) {

        this.callId = callId;
        return this;
    }

    /**
     * Unique ID for this Call, generated by FreeClimb.
     *
     * @return callId
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unique ID for this Call, generated by FreeClimb.")
    public String getCallId() {
        return callId;
    }

    public void setCallId(String callId) {
        this.callId = callId;
    }

    public CallControlWebhook accountId(String accountId) {

        this.accountId = accountId;
        return this;
    }

    /**
     * Account ID associated with your account.
     *
     * @return accountId
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Account ID associated with your account.")
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public CallControlWebhook conferenceId(String conferenceId) {

        this.conferenceId = conferenceId;
        return this;
    }

    /**
     * Unique ID of the Conference.
     *
     * @return conferenceId
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Unique ID of the Conference.")
    public String getConferenceId() {
        return conferenceId;
    }

    public void setConferenceId(String conferenceId) {
        this.conferenceId = conferenceId;
    }

    public CallControlWebhook digits(String digits) {

        this.digits = digits;
        return this;
    }

    /**
     * String of digits entered by the participant.
     *
     * @return digits
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "String of digits entered by the participant.")
    public String getDigits() {
        return digits;
    }

    public void setDigits(String digits) {
        this.digits = digits;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CallControlWebhook callControlWebhook = (CallControlWebhook) o;
        return Objects.equals(this.requestType, callControlWebhook.requestType)
                && Objects.equals(this.callId, callControlWebhook.callId)
                && Objects.equals(this.accountId, callControlWebhook.accountId)
                && Objects.equals(this.conferenceId, callControlWebhook.conferenceId)
                && Objects.equals(this.digits, callControlWebhook.digits)
                && super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(requestType, callId, accountId, conferenceId, digits, super.hashCode());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CallControlWebhook {\n");
        sb.append("    ").append(toIndentedString(super.toString())).append("\n");
        sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
        sb.append("    callId: ").append(toIndentedString(callId)).append("\n");
        sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
        sb.append("    conferenceId: ").append(toIndentedString(conferenceId)).append("\n");
        sb.append("    digits: ").append(toIndentedString(digits)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
