/*
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.github.freeclimbapi.models;

import com.github.freeclimbapi.enums.*;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** ExportRequest */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ExportRequest {
    public static String getDiscriminatorValue() {
        return null;
    }

    public static final String SERIALIZED_NAME_RESOURCE_TYPE = "resourceType";

    @SerializedName(SERIALIZED_NAME_RESOURCE_TYPE)
    private ExportResourceType resourceType;

    public static final String SERIALIZED_NAME_FORMAT = "format";

    @SerializedName(SERIALIZED_NAME_FORMAT)
    private List<String> format = null;

    public static final String SERIALIZED_NAME_OUTPUT = "output";

    @SerializedName(SERIALIZED_NAME_OUTPUT)
    private ExportRequestOutput output;

    public static final String SERIALIZED_NAME_QUERY = "query";

    @SerializedName(SERIALIZED_NAME_QUERY)
    private Object query;

    public ExportRequest() {}

    public ExportRequest resourceType(ExportResourceType resourceType) {

        this.resourceType = resourceType;
        return this;
    }

    /**
     * Get resourceType
     *
     * @return resourceType
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    public ExportResourceType getResourceType() {
        return resourceType;
    }

    public void setResourceType(ExportResourceType resourceType) {
        this.resourceType = resourceType;
    }

    public ExportRequest format(List<String> format) {

        this.format = format;
        return this;
    }

    public ExportRequest addFormatItem(String formatItem) {
        if (this.format == null) {
            this.format = new ArrayList<String>();
        }
        this.format.add(formatItem);
        return this;
    }

    /**
     * Get format
     *
     * @return format
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    public List<String> getFormat() {
        return format;
    }

    public void setFormat(List<String> format) {
        this.format = format;
    }

    public ExportRequest output(ExportRequestOutput output) {

        this.output = output;
        return this;
    }

    /**
     * Get output
     *
     * @return output
     */
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    public ExportRequestOutput getOutput() {
        return output;
    }

    public void setOutput(ExportRequestOutput output) {
        this.output = output;
    }

    public ExportRequest query(Object query) {

        this.query = query;
        return this;
    }

    /**
     * Get query
     *
     * @return query
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    public Object getQuery() {
        return query;
    }

    public void setQuery(Object query) {
        this.query = query;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExportRequest exportRequest = (ExportRequest) o;
        return Objects.equals(this.resourceType, exportRequest.resourceType)
                && Objects.equals(this.format, exportRequest.format)
                && Objects.equals(this.output, exportRequest.output)
                && Objects.equals(this.query, exportRequest.query);
    }

    @Override
    public int hashCode() {
        return Objects.hash(resourceType, format, output, query);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ExportRequest {\n");
        sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
        sb.append("    format: ").append(toIndentedString(format)).append("\n");
        sb.append("    output: ").append(toIndentedString(output)).append("\n");
        sb.append("    query: ").append(toIndentedString(query)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
