/*
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.github.freeclimbapi.models;

import com.github.freeclimbapi.enums.*;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.*;
import java.util.Objects;

/**
 * The engine to use for the TTS. The complete list of valid values for the engine attribute is
 * shown below.
 */
@ApiModel(
        description =
                "The engine to use for the TTS. The complete list of valid values for the engine"
                        + " attribute is shown below.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SayNeuralEngine {
    public static String getDiscriminatorValue() {
        return null;
    }

    public static final String SERIALIZED_NAME_NAME = "name";

    @SerializedName(SERIALIZED_NAME_NAME)
    private String name = "freeclimb.neural";

    public static final String SERIALIZED_NAME_PARAMETERS = "parameters";

    @SerializedName(SERIALIZED_NAME_PARAMETERS)
    private SayNeuralEngineParameters parameters;

    public SayNeuralEngine() {}

    public SayNeuralEngine name(String name) {

        this.name = name;
        return this;
    }

    /**
     * The name of the TTS engine to use. Set to &#x60;freeclimb.neural&#x60; to use the
     * freeclimb.neural TTS engine.
     *
     * @return name
     */
    @javax.annotation.Nullable
    @ApiModelProperty(
            value =
                    "The name of the TTS engine to use. Set to `freeclimb.neural` to use the"
                            + " freeclimb.neural TTS engine.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SayNeuralEngine parameters(SayNeuralEngineParameters parameters) {

        this.parameters = parameters;
        return this;
    }

    /**
     * Get parameters
     *
     * @return parameters
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    public SayNeuralEngineParameters getParameters() {
        return parameters;
    }

    public void setParameters(SayNeuralEngineParameters parameters) {
        this.parameters = parameters;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SayNeuralEngine sayNeuralEngine = (SayNeuralEngine) o;
        return Objects.equals(this.name, sayNeuralEngine.name)
                && Objects.equals(this.parameters, sayNeuralEngine.parameters);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, parameters);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SayNeuralEngine {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
