/*
 * FreeClimb API
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.github.freeclimbapi.models;

import com.github.freeclimbapi.enums.*;
import io.swagger.annotations.ApiModelProperty;
import java.util.*;
import java.util.Objects;

/** Webhook */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Webhook {
    public static String getDiscriminatorValue() {
        return null;
    }

    protected String requestType_noop;

    public Webhook() {
        this.requestType_noop = this.getClass().getSimpleName();
    }

    public Webhook requestType(String requestType) {

        this.requestType_noop = requestType;
        return this;
    }

    /**
     * Type of webhook request
     *
     * @return requestType
     */
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Type of webhook request")
    public String getRequestType() {
        return requestType_noop;
    }

    public void setRequestType(String requestType) {
        this.requestType_noop = requestType;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Webhook webhook = (Webhook) o;
        return Objects.equals(this.requestType_noop, webhook.requestType_noop);
    }

    @Override
    public int hashCode() {
        return Objects.hash(requestType_noop);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Webhook {\n");
        sb.append("    requestType_noop: ").append(toIndentedString(requestType_noop)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}
